name: myfirstapp
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.3.2


environment:
  sdk: '>=3.2.3 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  go_router: ^14.8.0
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.2
  cloud_firestore: ^5.6.6
  provider: ^6.1.4
  firebase_ui_auth: ^1.16.1

  http: ^1.2.0      # 用于API调用
  location: ^5.0.3  # 获取设备定位
  permission_handler: ^11.3.0 # 处理权限
  sensors_plus: ^4.0.0 # 添加传感器支持

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/introductionfigure.jpg
    - assets/intro.png
    - assets/clothes/short T.png
    - assets/clothes/T-shirt.jpg
    - assets/clothes/sweater.jpg
    - assets/clothes/knitwear.jpg
    - assets/clothes/hoodies.jpg
    - assets/clothes/wool sweater.jpg
    - assets/clothes/suit jacket.jpg
    - assets/clothes/jean jacket.png
    - assets/clothes/light down jacket.png
    - assets/clothes/down jacket.jpg
    - assets/clothes/jeans.jpg
    - assets/clothes/trousers.jpg
    - assets/clothes/cotton-wadded trousers.jpg
    - assets/clothes/fleece pants.jpg
    - assets/clothes/down pants.png
    - assets/clothes/shorts.png
    - assets/icon/closet.png
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: PlaywriteAUSA
      fonts:
        - asset: assets/fonts/PlaywriteAUSA-Regular.ttf

  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/closet.png"  # 根据你实际图标路径修改
  adaptive_icon_background: "#FFFFFF"
