// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZQgBXRCb5Ih3aZPBJTaFQFgaALBaNkZU',
    appId: '1:141335770338:web:bbca9cf893d4c88219dabb',
    messagingSenderId: '141335770338',
    projectId: 'weatherfit-ad465',
    authDomain: 'weatherfit-ad465.firebaseapp.com',
    storageBucket: 'weatherfit-ad465.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCr7TS5GxTyDGkahIOC3ynX1LkrRZARIpc',
    appId: '1:141335770338:android:15cb5174d88fe33a19dabb',
    messagingSenderId: '141335770338',
    projectId: 'weatherfit-ad465',
    storageBucket: 'weatherfit-ad465.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGVtv5tdl6Ta_UzRQ-hnYk7VkQE5HrNPc',
    appId: '1:141335770338:ios:240edc1558d2f20b19dabb',
    messagingSenderId: '141335770338',
    projectId: 'weatherfit-ad465',
    storageBucket: 'weatherfit-ad465.firebasestorage.app',
    iosBundleId: 'com.example.myfirstapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBGVtv5tdl6Ta_UzRQ-hnYk7VkQE5HrNPc',
    appId: '1:141335770338:ios:240edc1558d2f20b19dabb',
    messagingSenderId: '141335770338',
    projectId: 'weatherfit-ad465',
    storageBucket: 'weatherfit-ad465.firebasestorage.app',
    iosBundleId: 'com.example.myfirstapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDZQgBXRCb5Ih3aZPBJTaFQFgaALBaNkZU',
    appId: '1:141335770338:web:d8dfebf5493b704f19dabb',
    messagingSenderId: '141335770338',
    projectId: 'weatherfit-ad465',
    authDomain: 'weatherfit-ad465.firebaseapp.com',
    storageBucket: 'weatherfit-ad465.firebasestorage.app',
  );
}